name: Publish stable docker image

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push-image:
    name: Build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest stable Cura release URL
        id: get_latest_stable_cura_url
        run: |
          STABLE_RELEASE_URL=$(curl -s https://api.github.com/repos/Ultimaker/Cura/releases | jq -r --arg VERSION "${{ vars.LATEST_STABLE_CURA_VERSION }}" '.[] | select(.tag_name == $VERSION) | .assets[] | select(.name | test("X64\\.AppImage$")) | .browser_download_url')
          echo "stable_release_url=$STABLE_RELEASE_URL" >> $GITHUB_OUTPUT
          echo "stable_version=${{ vars.LATEST_STABLE_CURA_VERSION }}" >> $GITHUB_OUTPUT
          echo "Download url: $STABLE_RELEASE_URL"

      - name: Get latest baseimage-gui version
        id: get_latest_baseimagegui_version
        run: |
          LATEST_BASEIMAGEGUI_VERSION=$(curl -s https://api.github.com/repos/jlesage/docker-baseimage-gui/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "latest_baseimagegui_version=$LATEST_BASEIMAGEGUI_VERSION" >> $GITHUB_OUTPUT
          echo "latest baseimagegui version: $LATEST_BASEIMAGEGUI_VERSION"
          echo "latest stable baseimagegui version: ${{ vars.LATEST_STABLE_BASEIMAGEGUI_VERSION }}"

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            CURA_VERSION=${{ vars.LATEST_STABLE_CURA_VERSION }}
            BASEIMAGE_VERSION=${{ steps.get_latest_baseimagegui_version.outputs.latest_baseimagegui_version }}
            BASEIMAGE_VERSION=${{ vars.LATEST_STABLE_BASEIMAGEGUI_VERSION }} # Overwrite with stable vaersion
          tags: |
            ghcr.io/doganm95/cura-evolved:${{ vars.LATEST_STABLE_CURA_VERSION }}-${{ github.run_number }}
            ghcr.io/doganm95/cura-evolved:${{ github.sha }}
            ghcr.io/doganm95/cura-evolved:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ vars.LATEST_STABLE_CURA_VERSION }}
