name: Publish Docker image

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    outputs:
      cura_version: ${{ steps.get_version.outputs.cura_version }}
    steps:
      - name: check_out_repo
        uses: actions/checkout@v2
      
      - name: Read current Cura version from file
        id: read_version
        run: |
          CURRENT_CURA_VERSION=$(cat current_cura_version)
          echo "Current version: $CURRENT_CURA_VERSION"

      - name: Get latest Cura release tag
        id: get_latest_version
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Ultimaker/Cura/releases/latest | jq -r '.tag_name')
          echo "Latest release: $LATEST_RELEASE"
      
      - name: Compare versions and update if needed
        if: github.event_name == 'schedule'
        run: |
          echo "Comparing $LATEST_RELEASE with $CURRENT_CURA_VERSION"
          if [ "$LATEST_RELEASE" != "$CURRENT_CURA_VERSION" ]; then
            echo "$LATEST_RELEASE" > "$CURRENT_CURA_VERSION"
            git config --global user.name 'DoganM95'
            git config --global user.email 'actions@github.com'
            git add current_cura_version
            git commit -m "Update Cura to $LATEST_RELEASE"
            git push
          fi
        
      - name: Set Cura version output
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            # If the workflow is triggered by a push, use the latest release version
            echo "::set-output name=cura_version::$LATEST_RELEASE"
          else
            # Otherwise, use the current version from the file
            echo "::set-output name=cura_version::$(cat current_cura_version)"
          fi

  build-and-push-image:
    name: Build and push docker image to ghcr.io
    needs: check-new-release
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/doganm95/cura-evolved:${{ needs.check-new-release.outputs.cura_version }}
            ghcr.io/doganm95/cura-evolved:${{ github.sha }}
            ghcr.io/doganm95/cura-evolved:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ needs.check-new-release.outputs.cura_version }}
