name: Publish stable docker image

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push-image:
    name: Build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest versions
        id: get_latest_versions
        run: |
          # Fetch latest Cura release version
          LATEST_CURA_VERSION=$(curl -s https://api.github.com/repos/Ultimaker/Cura/releases | jq -r '[.[] | select(.prerelease == false)] | first(.tag_name)')
          echo "latest_cura_version=$LATEST_CURA_VERSION" >> $GITHUB_OUTPUT
          
          # Fetch latest baseimage-gui version
          LATEST_BASEIMAGEGUI_VERSION=$(curl -s https://api.github.com/repos/jlesage/docker-baseimage-gui/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "latest_baseimagegui_version=$LATEST_BASEIMAGEGUI_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            CURA_VERSION=${{ steps.get_latest_versions.outputs.latest_cura_version }}
            BASEIMAGE_VERSION=${{ steps.get_latest_versions.outputs.latest_baseimagegui_version }}
          tags: |
            ghcr.io/doganm95/cura-evolved:${{ steps.get_latest_versions.outputs.latest_cura_version }}-${{ github.run_number }}
            ghcr.io/doganm95/cura-evolved:${{ github.sha }}
            ghcr.io/doganm95/cura-evolved:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.get_latest_versions.outputs.latest_cura_version }}
