name: Publish Docker image

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    outputs:
      cura_version: ${{ steps.latest_version.outputs.LATEST_VERSION }}
      update_needed: ${{ steps.set_update_needed.outputs.update_needed }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Get latest Ultimaker Cura release tag
        id: latest_version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/Ultimaker/Cura/releases/latest | jq -r '.tag_name')
          echo "Latest release: $latest_release"
          echo "LATEST_VERSION=$latest_release" >> $GITHUB_ENV
      
      - name: Compare versions and determine if an update is needed
        if: github.event_name == 'schedule'
        id: compare_versions
        run: |
          current_cura_version=$(cat current_cura_version)
          if [[ "$latest_release" > "$current_cura_version" ]]; then
            echo "New Ultimaker Cura version available: $latest_release"
            echo "$latest_release" > current_cura_version
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add current_cura_version
            git commit -m "Update Ultimaker Cura version to $latest_release"
            git push
            echo "update_needed=true" >> $GITHUB_ENV
          else
            echo "Ultimaker Cura is up-to-date with version $current_cura_version"
            echo "update_needed=false" >> $GITHUB_ENV
          fi
      
      - name: Set output for update_needed
        id: set_update_needed
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "::set-output name=update_needed::true"
          else
            echo "update_needed=$(< $GITHUB_ENV)" 
            echo "::set-output name=update_needed::$update_needed"
          fi

  build-and-push-image:
    name: Build and push docker image to ghcr.io
    needs: check-new-release
    if: needs.check-new-release.outputs.update_needed == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/doganm95/cura-evolved:${{ needs.check-new-release.outputs.cura_version }}
            ghcr.io/doganm95/cura-evolved:${{ github.sha }}
            ghcr.io/doganm95/cura-evolved:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ needs.check-new-release.outputs.cura_version }}
