name: Publish stable docker image

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    outputs:
      stable_release_url: ${{ steps.get_latest_stable_cura_url.outputs.stable_release_url }}
      cura_version: ${{ steps.read_stable_version.outputs.cura_version }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read stable Cura version from file
        id: read_stable_version
        run: |
          LATEST_STABLE_CURA_VERSION=$(cat latest_stable_cura_version)
          echo "LATEST_STABLE_CURA_VERSION=$LATEST_STABLE_CURA_VERSION" >> $GITHUB_ENV
          echo "Latest stable Cura version: $LATEST_STABLE_CURA_VERSION"
          echo "cura_version=$LATEST_STABLE_CURA_VERSION" >> $GITHUB_OUTPUT
      - name: Get latest stable Cura release
        id: get_latest_stable_cura_url
        run: |
          STABLE_RELEASE_URL=$(curl -s https://api.github.com/repos/Ultimaker/Cura/releases | jq -r --arg VERSION "$LATEST_STABLE_CURA_VERSION" '.[] | select(.tag_name == $VERSION) | .assets[] | select(.name | test("X64\\.AppImage$")) | .browser_download_url')
          echo "stable_release_url=$STABLE_RELEASE_URL" >> $GITHUB_OUTPUT
          echo "Stable release url: $STABLE_RELEASE_URL"
          touch download_url.txt && echo "$STABLE_RELEASE_URL" > download_url.txt

  build-and-push-image:
    name: Build and push docker image to ghcr.io
    needs: check-new-release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check previous jobs output
        run: |
          echo "Cura version to use: ${{ needs.check-new-release.outputs.cura_version }}"
          echo "Cura url to use: ${{ needs.check-new-release.outputs.stable_release_url }}"
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/doganm95/cura-evolved:${{ needs.check-new-release.outputs.cura_version }}-${{ github.run_number }}
            ghcr.io/doganm95/cura-evolved:${{ github.sha }}
            ghcr.io/doganm95/cura-evolved:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ needs.check-new-release.outputs.cura_version }}
